services:
  - type: web
    name: flodon-discord-bot
    env: node
    plan: free
    rootDir: apps/discord-bot
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_VERSION
        value: 20.x

  - type: web
    name: flodon-internal-software
    env: node
    plan: free
    rootDir: apps/internal-software
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_VERSION
        value: 20.x
